Login Flow, APIs Authentication and Cookies Removal
EmeraldLabs/chatpdf-gpt pull request #38
Opened 2023-10-27 12:58 UTC by irfanmurtaza-el

- Login Page is Designed
- Home Page UI is Updated
- Document Page UI is Updated
- Removed Unnecessary Menu links and Icons
- Implement Auth Context
- Integrated AWS Congnito SDK on Frontend for Only Login
- Implemented Cognito Access Token Verification Process in APIs
- Delete Cookies Dependencies from Front-end and Back-end Side (POST Dpcument, GET Documents List, DELETE Document APIs are made secure)

2023-10-27 14:31 UTC, naqi requested changes

2023-10-27 14:31 UTC, naqi commented on context/credentials-context.tsx
> +  openaiApiKey: "",
if these are empty where are they initialized?

2023-10-27 14:31 UTC, naqi commented on context/credentials-context.tsx
> +  openaiApiKey: "",
Do we need to keep this variable?

2023-10-27 14:31 UTC, naqi commented on jwks.json
> +{
what is this for? should this be in repo?

2023-10-31 10:03 UTC, irfanmurtaza-el commented on jwks.json
> +{
This is public JSON Web Key to verify access token, Here is the Reference link : https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

2023-10-31 10:14 UTC, irfanmurtaza-el commented on context/credentials-context.tsx
> +  openaiApiKey: "",
Deleted Context for cookies

2023-11-07 07:09 UTC, amiryamin450 approved these changes

2023-11-07 07:09 UTC, merged